baseURL = 'https://momansour.me'
languageCode = 'en-us'
title = 'mo@mansour'
theme = 'hugo-theme-console'

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # remove or comment this parameter to disable animation
  animateStyle = "animated zoomIn fast" 
  [params.author]
    email = 'hi@momansour.me'
    name = 'Mo Mansour'
    github = 'itsmohmans'
    linkedin = 'mansourmoh'

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "projects/"
  url = "projects/"
